// <auto-generated />
namespace MyHotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RoomOptions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoomOptions));
        
        string IMigrationMetadata.Id
        {
            get { return "202006091609304_RoomOptions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
